In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("nycflights.csv")

In [3]:
df.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,1/1/2013 5:00
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,1/1/2013 5:00
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,1/1/2013 5:00
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,1/1/2013 5:00
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,1/1/2013 6:00

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
year              336776 non-null int64
month             336776 non-null int64
day               336776 non-null int64
dep_time          328521 non-null float64
sched_dep_time    336776 non-null int64
dep_delay         328521 non-null float64
arr_time          328063 non-null float64
sched_arr_time    336776 non-null int64
arr_delay         327346 non-null float64
carrier           336776 non-null object
flight            336776 non-null int64
tailnum           334264 non-null object
origin            336776 non-null object
dest              336776 non-null object
air_time          327346 non-null float64
distance          336776 non-null int64
hour              336776 non-null int64
minute            336776 non-null int64
time_hour         336776 non-null object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

In [5]:
df.dep_time[10:25]  # it is a float because we have missing values that are stored as NaNs. NaNs are always floats
# also this time column is terrible
# 559.0 represent 5:59 AM
# 600.0 represent 6:00 AM
# we need to parse this into pieces so we can turn them into actual hours and minutes

10    558.0
11    558.0
12    558.0
13    558.0
14    559.0
15    559.0
16    559.0
17    600.0
18    600.0
19    601.0
20    602.0
21    602.0
22    606.0
23    606.0
24    607.0
Name: dep_time, dtype: float64

In [6]:
# unfortunately, some of the values in departure time ar missing and stored as NaN
df.dep_time[np.isnan(df.dep_time)]  # logical vector

838      NaN
839      NaN
840      NaN
841      NaN
1777     NaN
1778     NaN
1779     NaN
1780     NaN
1781     NaN
1782     NaN
1783     NaN
1784     NaN
2689     NaN
2690     NaN
2691     NaN
2692     NaN
2693     NaN
2694     NaN
2695     NaN
2696     NaN
2697     NaN
2698     NaN
3608     NaN
3609     NaN
3610     NaN
3611     NaN
3612     NaN
3613     NaN
4331     NaN
4332     NaN
          ..
331218   NaN
332185   NaN
332186   NaN
332187   NaN
332188   NaN
332189   NaN
332190   NaN
332191   NaN
332192   NaN
332193   NaN
332194   NaN
333188   NaN
333189   NaN
333190   NaN
334183   NaN
334184   NaN
334185   NaN
334186   NaN
334866   NaN
334867   NaN
334868   NaN
335780   NaN
335781   NaN
335782   NaN
336770   NaN
336771   NaN
336772   NaN
336773   NaN
336774   NaN
336775   NaN
Name: dep_time, Length: 8255, dtype: float64

In [7]:
# One option is to remove all flights with NaN departure times into a new table
# keep only the flights that do not have missing times

missing_dep = df.loc[np.isnan(df.dep_time), ]

In [8]:
departed = df.loc[~np.isnan(df.dep_time),]

In [9]:
missing_dep.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8255 entries, 838 to 336775
Data columns (total 19 columns):
year              8255 non-null int64
month             8255 non-null int64
day               8255 non-null int64
dep_time          0 non-null float64
sched_dep_time    8255 non-null int64
dep_delay         0 non-null float64
arr_time          0 non-null float64
sched_arr_time    8255 non-null int64
arr_delay         0 non-null float64
carrier           8255 non-null object
flight            8255 non-null int64
tailnum           5743 non-null object
origin            8255 non-null object
dest              8255 non-null object
air_time          0 non-null float64
distance          8255 non-null int64
hour              8255 non-null int64
minute            8255 non-null int64
time_hour         8255 non-null object
dtypes: float64(5), int64(9), object(5)
memory usage: 1.3+ MB

In [10]:
departed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 328521 entries, 0 to 336769
Data columns (total 19 columns):
year              328521 non-null int64
month             328521 non-null int64
day               328521 non-null int64
dep_time          328521 non-null float64
sched_dep_time    328521 non-null int64
dep_delay         328521 non-null float64
arr_time          328063 non-null float64
sched_arr_time    328521 non-null int64
arr_delay         327346 non-null float64
carrier           328521 non-null object
flight            328521 non-null int64
tailnum           328521 non-null object
origin            328521 non-null object
dest              328521 non-null object
air_time          327346 non-null float64
distance          328521 non-null int64
hour              328521 non-null int64
minute            328521 non-null int64
time_hour         328521 non-null object
dtypes: float64(5), int64(9), object(5)
memory usage: 50.1+ MB

In [11]:
departed.dep_time.values.astype("i").astype("str") # we take the departure time column, take the values, make it into an integer
# and then make it into a string

array(['517', '533', '542', ..., '2241', '2307', '2349'], dtype='<U11')

In [12]:
time = departed.dep_time.values.astype("i").astype("str")
print(time[:10])

['517' '533' '542' '544' '554' '554' '555' '557' '557' '558']

In [13]:
a = "hello"
print(a[-2:])  # once they are a string, we can use slicing to take the last two values as the minute

lo

In [14]:
m = np.array([string[-2:] for string in time]) # list comprehension
print(m[:10])

['17' '33' '42' '44' '54' '54' '55' '57' '57' '58']

In [15]:
h = np.array([string[:-2] for string in time]) # list comprehension
# we'll take everything up to the last two values as the hour

In [16]:
dep_date_time = pd.to_datetime(departed.year.astype('str') + "-" +
                               departed.month.astype('str') + "-" + 
                               departed.day.astype('str') + " " + 
                               h + ":" + m , format = "%Y-%m-%d %H:%M")

ValueError: time data '2013-1-2 :42' doesn't match format specified

In [18]:
# we get an error because there are times without an hour
departed.loc[h == ""]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
842,2013,1,2,42.0,2359,43.0,518.0,442,36.0,B6,707,N580JB,JFK,SJU,189.0,1598,23,59,1/2/2013 23:00
1785,2013,1,3,32.0,2359,33.0,504.0,442,22.0,B6,707,N763JB,JFK,SJU,193.0,1598,23,59,1/3/2013 23:00
1786,2013,1,3,50.0,2145,185.0,203.0,2311,172.0,B6,104,N329JB,JFK,BUF,58.0,301,21,45,1/3/2013 21:00
2699,2013,1,4,25.0,2359,26.0,505.0,442,23.0,B6,707,N554JB,JFK,SJU,194.0,1598,23,59,1/4/2013 23:00
3614,2013,1,5,14.0,2359,15.0,503.0,445,18.0,B6,739,N592JB,JFK,PSE,201.0,1617,23,59,1/5/2013 23:00
3615,2013,1,5,37.0,2230,127.0,341.0,131,130.0,B6,11,N527JB,JFK,FLL,163.0,1069,22,30,1/5/2013 22:00
4334,2013,1,6,16.0,2359,17.0,451.0,442,9.0,B6,707,N606JB,JFK,SJU,197.0,1598,23,59,1/6/2013 23:00
5166,2013,1,7,49.0,2359,50.0,531.0,444,47.0,B6,739,N598JB,JFK,PSE,202.0,1617,23,59,1/7/2013 23:00
6998,2013,1,9,2.0,2359,3.0,432.0,444,-12.0,B6,739,N603JB,JFK,PSE,193.0,1617,23,59,1/9/2013 23:00
6999,2013,1,9,8.0,2359,9.0,432.0,437,-5.0,B6,727,N563JB,JFK,BQN,188.0,1576,23,59,1/9/2013 23:00
7900,2013,1,10,3.0,2359,4.0,426.0,437,-11.0,B6,727,N571JB,JFK,BQN,183.0,1576,23,59,1/10/2013 23:00
7901,2013,1,10,16.0,2359,17.0,447.0,444,3.0,B6,739,N564JB,JFK,PSE,191.0,1617,23,59,1/10/2013 23:00
8832,2013,1,11,11.0,2359,12.0,436.0,444,-8.0,B6,739,N779JB,JFK,PSE,190.0,1617,23,59,1/11/2013 23:00
8833,2013,1,11,19.0,2359,20.0,439.0,437,2.0,B6,727,N705JB,JFK,BQN,180.0,1576,23,59,1/11/2013 23:00
9762,2013,1,12,30.0,2359,31.0,506.0,444,22.0,B6,739,N705JB,JFK,PSE,192.0,1617,23,59,1/12/2013 23:00
10452,2013,1,13,1.0,2249,72.0,108.0,2357,71.0,B6,22,N206JB,JFK,SYR,41.0,209,22,49,1/13/2013 22:00
10453,2013,1,13,2.0,2359,3.0,502.0,444,18.0,B6,739,N523JB,JFK,PSE,197.0,1617,23,59,1/13/2013 23:00
10454,2013,1,13,3.0,2030,213.0,340.0,2350,230.0,B6,1069,N281JB,JFK,AUS,243.0,1521,20,30,1/13/2013 20:00
10455,2013,1,13,10.0,2135,155.0,305.0,36,149.0,B6,11,N595JB,JFK,FLL,144.0,1069,21,35,1/13/2013 21:00
10456,2013,1,13,20.0,2359,21.0,505.0,437,28.0,B6,727,N613JB,JFK,BQN,181.0,1576,23,59,1/13/2013 23:00
10457,2013,1,13,48.0,2140,188.0,203.0,2306,177.0,B6,104,N192JB,JFK,BUF,55.0,301,21,40,1/13/2013 21:00
10458,2013,1,13,52.0,2253,119.0,223.0,15,128.0,B6,112,N629JB,JFK,BUF,53.0,301,22,53,1/13/2013 22:00
13102,2013,1,16,2.0,2125,157.0,119.0,2250,149.0,MQ,4660,N504MQ,LGA,BNA,121.0,764,21,25,1/16/2013 21:00
13103,2013,1,16,3.0,1946,257.0,212.0,2154,258.0,EV,4536,N16987,EWR,CVG,111.0,569,19,46,1/16/2013 19:00
18226,2013,1,22,5.0,2359,6.0,452.0,444,8.0,B6,739,N659JB,JFK,PSE,205.0,1617,23,59,1/22/2013 23:00
20013,2013,1,24,37.0,2107,210.0,236.0,2322,194.0,EV,3819,N16561,EWR,SDF,104.0,642,21,7,1/24/2013 21:00
20014,2013,1,24,45.0,2159,166.0,147.0,2306,161.0,EV,4322,N12921,EWR,PWM,49.0,284,21,59,1/24/2013 21:00
20938,2013,1,25,15.0,1815,360.0,208.0,1958,370.0,9E,4019,N8646A,JFK,RIC,56.0,288,18,15,1/25/2013 18:00
20939,2013,1,25,17.0,2249,88.0,119.0,2357,82.0,B6,22,N228JB,JFK,SYR,45.0,209,22,49,1/25/2013 22:00
20940,2013,1,25,26.0,1850,336.0,225.0,2055,330.0,US,1491,N181UW,LGA,CLT,82.0,544,18,50,1/25/2013 18:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309923,2013,9,2,15.0,2359,16.0,417.0,344,33.0,B6,1503,N805JB,JFK,SJU,210.0,1598,23,59,9/2/2013 23:00
309924,2013,9,2,18.0,2100,198.0,253.0,2336,197.0,B6,499,N606JB,LGA,MCO,128.0,950,21,0,9/2/2013 21:00
309925,2013,9,2,28.0,2130,178.0,327.0,14,193.0,B6,1371,N636JB,LGA,FLL,149.0,1076,21,30,9/2/2013 21:00
309926,2013,9,2,53.0,2030,263.0,200.0,2155,245.0,WN,1707,N939WN,LGA,MDW,110.0,725,20,30,9/2/2013 20:00
309927,2013,9,2,57.0,2025,272.0,220.0,2158,262.0,FL,357,N998AT,LGA,CAK,65.0,397,20,25,9/2/2013 20:00
313722,2013,9,6,8.0,2359,9.0,421.0,350,31.0,B6,745,N655JB,JFK,PSE,216.0,1617,23,59,9/6/2013 23:00
314689,2013,9,7,20.0,2359,21.0,723.0,350,NaN,B6,745,N593JB,JFK,PSE,NaN,1617,23,59,9/7/2013 23:00
318237,2013,9,11,11.0,2034,217.0,130.0,2209,201.0,9E,4127,N8965E,JFK,IAD,54.0,228,20,34,9/11/2013 20:00
318238,2013,9,11,15.0,2245,90.0,111.0,2351,80.0,B6,1816,N284JB,JFK,SYR,39.0,209,22,45,9/11/2013 22:00
318239,2013,9,11,23.0,2359,24.0,432.0,350,42.0,B6,745,N665JB,JFK,PSE,226.0,1617,23,59,9/11/2013 23:00
319184,2013,9,12,2.0,2103,179.0,114.0,2226,168.0,EV,4119,N13988,EWR,RIC,48.0,277,21,3,9/12/2013 21:00
319185,2013,9,12,4.0,2245,79.0,112.0,2351,81.0,B6,1816,N284JB,JFK,SYR,42.0,209,22,45,9/12/2013 22:00
319186,2013,9,12,5.0,2100,185.0,214.0,2322,172.0,DL,1247,N906DL,LGA,ATL,102.0,762,21,0,9/12/2013 21:00
319187,2013,9,12,6.0,1935,271.0,231.0,2232,239.0,DL,1485,N916DE,LGA,MCO,125.0,950,19,35,9/12/2013 19:00
319188,2013,9,12,8.0,2030,218.0,128.0,2203,205.0,FL,357,N717JL,LGA,CAK,64.0,397,20,30,9/12/2013 20:00
319189,2013,9,12,12.0,1410,602.0,207.0,1635,572.0,FL,350,N956AT,LGA,ATL,98.0,762,14,10,9/12/2013 14:00
319190,2013,9,12,16.0,2100,196.0,114.0,2211,183.0,US,2164,N947UW,LGA,BOS,38.0,184,21,0,9/12/2013 21:00
319191,2013,9,12,26.0,2000,266.0,313.0,2300,253.0,VX,415,N839VA,JFK,LAX,326.0,2475,20,0,9/12/2013 20:00
319192,2013,9,12,33.0,1440,593.0,213.0,1642,571.0,DL,1819,N922DL,LGA,MSP,140.0,1020,14,40,9/12/2013 14:00
319193,2013,9,12,39.0,2359,40.0,423.0,350,33.0,B6,745,N806JB,JFK,PSE,205.0,1617,23,59,9/12/2013 23:00
319194,2013,9,12,39.0,2105,214.0,304.0,17,167.0,DL,1643,N624AG,JFK,SEA,301.0,2422,21,5,9/12/2013 21:00
319195,2013,9,12,48.0,1942,306.0,329.0,2250,279.0,B6,1271,N564JB,LGA,FLL,142.0,1076,19,42,9/12/2013 19:00
319196,2013,9,12,50.0,2255,115.0,155.0,2358,117.0,B6,718,N592JB,JFK,BOS,37.0,187,22,55,9/12/2013 22:00
319197,2013,9,12,53.0,2245,128.0,150.0,2356,114.0,B6,108,N247JB,JFK,PWM,42.0,273,22,45,9/12/2013 22:00
320176,2013,9,13,3.0,2200,123.0,110.0,2312,118.0,9E,3525,N917XJ,LGA,SYR,36.0,198,22,0,9/13/2013 22:00
325683,2013,9,19,10.0,2103,187.0,109.0,2226,163.0,EV,4119,N16918,EWR,RIC,43.0,277,21,3,9/19/2013 21:00
326675,2013,9,20,9.0,2250,79.0,123.0,7,76.0,B6,2002,N190JB,JFK,BUF,48.0,301,22,50,9/20/2013 22:00
326676,2013,9,20,31.0,2017,254.0,146.0,2159,227.0,UA,1464,N25705,EWR,CLE,58.0,404,20,17,9/20/2013 20:00
326677,2013,9,20,47.0,2359,48.0,447.0,350,57.0,B6,745,N643JB,JFK,PSE,209.0,1617,23,59,9/20/2013 23:00
327669,2013,9,21,8.0,2359,9.0,350.0,350,0.0,B6,745,N579JB,JFK,PSE,204.0,1617,23,59,9/21/2013 23:00

In [19]:
h[h == ""] = "0" # we substitue anything where the hour is a blank string with 0. This is for flights

In [20]:
dep_date_time = pd.to_datetime(departed.year.astype('str') + "-" +
                               departed.month.astype('str') + "-" + 
                               departed.day.astype('str') + " " + 
                               h + ":" + m , format = "%Y-%m-%d %H:%M")

ValueError: time data '2013-10-30 24:00' doesn't match format specified

In [21]:
# we still get an error. This time, we have times that are 24:00
# Let's take a closer look:
departed.loc[h == '24', ]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
54966,2013,10,30,2400.0,2359,1.0,327.0,337,-10.0,B6,839,N661JB,JFK,BQN,182.0,1576,23,59,10/30/2013 23:00
80973,2013,11,27,2400.0,2359,1.0,515.0,445,30.0,B6,745,N629JB,JFK,PSE,230.0,1617,23,59,11/27/2013 23:00
87893,2013,12,5,2400.0,2359,1.0,427.0,440,-13.0,B6,1503,N587JB,JFK,SJU,182.0,1598,23,59,12/5/2013 23:00
91492,2013,12,9,2400.0,2359,1.0,432.0,440,-8.0,B6,1503,N705JB,JFK,SJU,195.0,1598,23,59,12/9/2013 23:00
91493,2013,12,9,2400.0,2250,70.0,59.0,2356,63.0,B6,1816,N187JB,JFK,SYR,41.0,209,22,50,12/9/2013 22:00
95379,2013,12,13,2400.0,2359,1.0,432.0,440,-8.0,B6,1503,N587JB,JFK,SJU,192.0,1598,23,59,12/13/2013 23:00
100795,2013,12,19,2400.0,2359,1.0,434.0,440,-6.0,B6,1503,N561JB,JFK,SJU,193.0,1598,23,59,12/19/2013 23:00
109532,2013,12,29,2400.0,1700,420.0,302.0,2025,397.0,AA,2379,N3GMAA,LGA,MIA,161.0,1096,17,0,12/29/2013 17:00
117373,2013,2,7,2400.0,2359,1.0,432.0,436,-4.0,B6,727,N559JB,JFK,BQN,186.0,1576,23,59,2/7/2013 23:00
117374,2013,2,7,2400.0,2359,1.0,443.0,444,-1.0,B6,739,N766JB,JFK,PSE,194.0,1617,23,59,2/7/2013 23:00
120677,2013,2,11,2400.0,2135,145.0,251.0,35,136.0,B6,11,N656JB,JFK,FLL,149.0,1069,21,35,2/11/2013 21:00
150301,2013,3,15,2400.0,2359,1.0,324.0,338,-14.0,B6,727,N636JB,JFK,BQN,186.0,1576,23,59,3/15/2013 23:00
156854,2013,3,22,2400.0,2358,2.0,339.0,338,1.0,B6,707,N641JB,JFK,SJU,189.0,1598,23,58,3/22/2013 23:00
159422,2013,3,25,2400.0,2355,5.0,339.0,340,-1.0,B6,739,N612JB,JFK,PSE,200.0,1617,23,55,3/25/2013 23:00
167030,2013,4,2,2400.0,2359,1.0,339.0,343,-4.0,B6,707,N656JB,JFK,SJU,192.0,1598,23,59,4/2/2013 23:00
169005,2013,4,4,2400.0,2355,5.0,347.0,345,2.0,B6,739,N508JB,JFK,PSE,199.0,1617,23,55,4/4/2013 23:00
183977,2013,4,20,2400.0,2359,1.0,338.0,339,-1.0,B6,727,N649JB,JFK,BQN,196.0,1576,23,59,4/20/2013 23:00
212941,2013,5,21,2400.0,2359,1.0,339.0,350,-11.0,B6,739,N527JB,JFK,PSE,199.0,1617,23,59,5/21/2013 23:00
238048,2013,6,17,2400.0,2145,135.0,102.0,2315,107.0,DL,985,N346NB,JFK,BOS,37.0,187,21,45,6/17/2013 21:00
256601,2013,7,7,2400.0,1950,250.0,107.0,2130,217.0,AA,363,N544AA,LGA,ORD,101.0,733,19,50,7/7/2013 19:00
262457,2013,7,13,2400.0,2245,75.0,101.0,2359,62.0,B6,1816,N334JB,JFK,SYR,40.0,209,22,45,7/13/2013 22:00
262458,2013,7,13,2400.0,2155,125.0,225.0,43,102.0,B6,425,N597JB,JFK,TPA,129.0,1005,21,55,7/13/2013 21:00
266385,2013,7,17,2400.0,2142,138.0,54.0,2259,115.0,EV,3832,N22971,EWR,DCA,37.0,199,21,42,7/17/2013 21:00
276812,2013,7,28,2400.0,2059,181.0,247.0,2322,205.0,DL,1247,N945DL,LGA,ATL,107.0,762,20,59,7/28/2013 20:00
276813,2013,7,28,2400.0,2359,1.0,411.0,344,27.0,B6,1503,N503JB,JFK,SJU,204.0,1598,23,59,7/28/2013 23:00
289412,2013,8,10,2400.0,2245,75.0,110.0,1,69.0,B6,234,N328JB,JFK,BTV,53.0,266,22,45,8/10/2013 22:00
299009,2013,8,20,2400.0,2359,1.0,354.0,350,4.0,B6,745,N708JB,JFK,PSE,201.0,1617,23,59,8/20/2013 23:00
310765,2013,9,2,2400.0,2359,1.0,411.0,340,31.0,B6,839,N828JB,JFK,BQN,217.0,1576,23,59,9/2/2013 23:00
319983,2013,9,12,2400.0,2000,240.0,203.0,2230,213.0,DL,1147,N910DE,LGA,ATL,101.0,762,20,0,9/12/2013 20:00

In [22]:
# hmm....
# These look like flights that were scheduled, and then took of a little bit late, perhaps the next day
# but the system records it as 24:00 hours
# We probably need to do some rethinking

# ... thiking ...

# Ok. I think I will attempt to use the scheduled time, and then use the departure delay to calculate the departure time
# I will convert the scheduled time to a date_time object, 
# then add the departure delay in minutes
# and get another date_time object for the departure time